### ISSUE TITLE
Add the .idea/ folder to the .gitignore file

### ISSUE THREAD

**Issue by ssfinney** [erwinsaget/the-pigeon-hole#1]
Hey Erwin!

That .idea directory is a folder that PHPStorm uses to cache stuff and build configuration around your project.

Since it changes a lot (and isn't directly related to your project), it's generally a good idea to tell git to ignore this directory.

You can do this by adding ```.idea/``` to your .gitignore file, and then use ```git rm -r .idea/``` to tell git to remove the directory from your source control.

**Comment by erwinsaget** [comment]
Done!
